scaffold-eth/scaffold-eth

- README.md
Right now, a user may exit the previous command to run the new one, this helps them know to have at least 3 terminal windows open.
> Make sure users know to use multiple terminal windows

- packages/react-app/src/SmartContractWallet.js
Current timeline is clipped on at least standard Macbook Pro display (although - seems it would be on any display). This pushes it over to not conflict with other text.
Note: Might have mobile considerations, but not sure how many people will be doing DApp development on mobile quite yet 😛 
**Current**:
**New**:
> Add a margin to ensure the timeline is visible

- packages/buidler/scripts/deploy.js
In case a smart contract implements an interface, budler will create an
artifact JSON file for that interface as well.
Attempt to call '.new()' on this artifact crashes the deployer srcipt.
> Prevent 'deploy.js' script from crashing on interface artifacts

- package.json
- packages/buidler/package.json
As stated in yarn documentation here:
https://classic.yarnpkg.com/en/docs/workspaces/#toc-limitations-caveats
"The package layout will be different between your workspace and what
your users will get." Unfortunately, 'budler' searches for plugins in
the project root's ./node_modules/ folder, which is not guaranteed to
work with yarn workspaces.
Declaring all buidler dependencies in a root package.json seems to
resolve the issue.
=====
Also, the buidler version is updated to include the following fix:
https://github.com/nomiclabs/buidler/pull/540
> Fix module hoisthing problem and avoid buggy version of buidler

- packages/react-app/src/InkCanvas.js
- packages/react-app/src/InkInfo.js
- Adding a "description" field for OpenSea - e.g. "A Nifty Ink by 0xE09750abE36beA8B2236E48C84BB9da7Ef5aA07c on Sat, 11 Jul 2020 19:49:42 GMT" (or will use ENS name if there is one)
- Turning the Limit field into a string (so OpenSea doesn't show it as a rank) - and add handling so the mint limit logic still works in the app
- Comment out the GSN meta transaction call (as we don't have the addresses from GSN yet)
> Better description, comment out GSN, Limit as string

- packages/react-app/src/hooks/ContractLoader.js
This is a fix to the unintentional removal the previous "names as keys" behaviour
> useContractLoader fix

- packages/react-app/src/App.jsx
Using `getDefaultProvider` we send some requests to other node services like Etherscan and Cloudflare which means fewer requests the provided api key.
> use ethers DefaultProvider to reduce load on api key

- package.json
- packages/buidler/.eslintrc.js
- packages/buidler/buidler.config.js
- packages/buidler/package.json
- packages/buidler/scripts/deploy.js
- packages/buidler/scripts/publish.js
- packages/buidler/scripts/watch.js
- packages/buidler/test/myTest.js
- packages/contracts/package.json
- packages/react-app/package.json
- yarn.lock
I've had a look at the buidler package so that we can hoover that up into CEA at some point.
This is another big PR but the highlights are
- packages are now named `@scaffold-eth/package`
- buidler is now installed inside the `@scaffold-eth/buidler` package
- yarn uses workspaces to call buidler scripts rather than cd-ing into the package.
- buidler package has been linted
- deploy, publish and watch scripts have been refactored for readability
> Refactor buidler package

- packages/buidler/buidler.config.js
- packages/buidler/package.json
- packages/buidler/scripts/deploy.js
- packages/buidler/scripts/watch.js
- packages/buidler/test/myTest.js
- yarn.lock
This PR fixes the bug meaning #32 had to be reverted as well as migrating to use ethers/waffle. I've changed the test to use `YourContract` rather than `SmartContractWallet` as well so it can be run straight away.
The issue was in these lines. Basically `forEach` wasn't playing nicely with async functions so the script finished before the contracts actually got deployed and no promises got resolved.
```
contractList
.filter((fileName) => isSolidity(fileName))
.forEach(async (fileName) => {
const contractName = fileName.replace(".sol", "");
const args = readArgumentsFile(contractName);
await deploy(contractName, args);
});
```
I've fixed this by explicitly enforcing that we wait for the promises to resolve (and contracts to be deployed) before attempting to deploy the next (or exiting the …
> Swap buidler package to use ethers/waffle over web3/truffle

- packages/buidler/package.json
Linux and recursively with node 14 throws TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM] in node-watch v0.6.3
Issue was patched in v0.6.4
Issue referred to here: [https://github.com/yuanchuan/node-watch/issues/94](https://github.com/yuanchuan/node-watch/issues/94)
> Upgrade node-watch package version

- packages/react-app/src/InkCanvas.js
This change makes it easy to play with react-canvas-draw from JS console.
Here is a snippet how that works:
```
drawingCanvas.current.points = [{x:0, y:0}, {x:drawingCanvas.current.canvas.drawing.width, y:drawingCanvas.current.canvas.drawing.height}]
drawingCanvas.current.saveLine({
brushColor: drawingCanvas.current.props.brushColor,
brushRadius: drawingCanvas.current.props.brushRadius
})
drawingCanvas.current.simulateDrawingLines({
lines: drawingCanvas.current.lines,
immediate: true
})
```
And the result:
https://nifty.ink/QmZBxNgPEWS3oQhuqHqxm6dM8iH8YbUreqSzcNGiEz1hmV
I tested it with my local front-end and xdai network
> React canvas object as a global var

- packages/react-app/src/InkCanvas.js
One-click button to fill background according to picked color, and another button to draw instant frames according to picked color and radius.
> Add 'Fill background' and 'Draw frame' functionality

- README.md
- packages/react-app/src/components/Contract/FunctionForm.jsx
Here is the minimal contract function that would show that the transaction hash is not shown. As a consequence, we will not be able to export it to Tenderly.
```
function getDivision(uint256 x, uint256 y) public returns (uint256) {
uint256 result = x / y;
map[msg.sender] = result;
return result;
}
```
Pass `y` as 0.
> feat: add gas estimation skipping ability and fork note for tenderly

- packages/react-app/src/App.jsx
Heavy **logging is reduced to actual state changes** using **two separate useEffect-hooks** for things that
a) change rarely (like your mainnet provider)
b) could change often: your balance and transactions
It also has branch-specific logging for the _buyer-mints-nft_ branch (commented out) and the master branch.
This should make the development on all branches less noisy. 🧘‍♂️
> Reduced console logging by utilizing useEffect - within App.jsx

- packages/react-app/src/components/Ramp.jsx
Was throwing an error because the keys were not unique (all `undefined`). I think `chainId` was the intended key.
Thank you for the unbelievably amazing project, by the way :smile:
> Use the correct prop as a key in Ramp.jsx

- packages/react-app/src/App.jsx
- packages/react-app/src/components/Balance.jsx
- packages/react-app/src/hooks/Balance.js
- packages/react-app/src/hooks/ContractReader.js
- packages/react-app/src/hooks/LookupAddress.js
- packages/react-app/src/hooks/OnBlock.js
- packages/react-app/src/hooks/Poller.js
- packages/react-app/src/hooks/index.js
- StaticJsonRpcProvider to reduce chainId polling (see this ethers issue https://github.com/ethers-io/ethers.js/issues/901 -this is fine in cases where we know the chainid is not going to change)
- Update useBalance and useContractReader to update on every new block, rather than on a set polling interval (using ethers.js `provider.on('block',listener)`
- Cache ENS for when we don't resolve a name to stop trying to fetch (we were only caching names that we resolved) - this is still a bit of a sprawling implementation in the local storage)
- Standardised the balance component to use `useBalance` (it had a home grown implementation)
> Polling fixes - reduce polling intensity

- packages/react-app/src/hooks/LocalStorage.js
- ttl is optional, in milliseconds
- lazy removal (only if a value is checked)
- expiry date is not returned
- potential breaking case where a non-TTL useLocalStorage stores a value that is an object with "expiry" and "value" as keys (will only return the value, not the expiry) but that is unlikely
> optional ttl on useLocalStorage

- README.md
Inverted the order on which the node and the react app is start.
Currently the react app was started first and it was throwing an error, because it was not finding the node running yet. As per described in [Issue 129](https://github.com/austintgriffith/scaffold-eth/issues/129).
> Fixed the quickstart terminal commands order

- .editorconfig
This ensures that many editors can automatically configure themselves to the right indentation style to be consistent with this codebase, as per https://editorconfig.org/
> Set up editor indentation correctly

- packages/hardhat/package.json
Reported in the scaffold-eth chat, Hardhat fork requires specifying `--network hardhat`. This also adds the no-deploy flag so contracts aren't auto-deployed
> Fix yarn fork

- packages/react-app/src/hooks/Balance.js
Balances are only updated when there is a new block. This is especially strange during local development where you don't get new blocks on an ongoing basis. This change updates the balance when the provider or address changes
> Update balance when provider / address changes

- packages/hardhat/hardhat.config.js
- packages/react-app/src/constants.js
Added Harmony testnet + mainnet networks. I have tested this end-to-end. Contract deployment and UI network switching function as expected. `yarn account` returns the correct balance.
[Harmony](https://www.harmony.one) is a sharded and open blockchain. Harmony is 100% EVM compatible and runs Ethereum applications with 2-second transaction finality and 100 times lower fees.
> New network: Harmony ONE

- packages/react-app/src/App.jsx
Uses `wallet_switchEthereumChain` before trying `wallet_addEthereumChain` according to [MM recommendation](https://docs.metamask.io/guide/rpc-api.html#usage-with-wallet-switchethereumchain)
A bit more details: `wallet_addEthereumChain` is for adding a chain, which fails for default chains (because chain are already in MM) and for localhost (because it's not HTTPS). The recommended method is to try and use the "switch" method, and if that - try adding a chain.
Testing: manually checking switching back and forth between a few networks, with MM only, so not sure how it will behave with other browser wallets.
> fix switching chains in metamask

- packages/react-app/src/hooks/ExchangePrice.js
resolve #308 preventing users from using the UI if the UniSwap fetch fails it's price retrieval.
> Add catch to DAI price fetch to prevent page crash

- packages/react-app/src/App.jsx
ReferenceError: parseEther is not defined
ethers.utils seem to be missing for parseEther on line 553.
> Fix: parseEther is not defined

- packages/react-app/src/App.jsx
This PR fixes a problem in the frontend of the challenge where "humanize-duration" is not instantiated
> fix: add required humanize-duration import

- .vscode/settings.json
fix https://github.com/scaffold-eth/scaffold-eth/issues/388
Make the following error go away in VSCode
> Update VSCode setting packageDefaultDependenciesDirectory

- packages/react-app/package.json
updated eth-hooks
- js docs were updated
- npm package readme has better docs
> updated eth-hooks to 2.3.8: js docs were updated

- README.md
Hey @codenamejason and @austintgriffith :wave: 
I'm wanting to do a class on this branch in the next Kernel block, which starts tomorrow (though the NFTeasy build guild that references this particular branch will prob only happen 4 weeks from now).
I ran into some issues following the guide and so have made the changes I needed to get running here, hopefully it helps.
In particular, I had to upload the default art first because of [this](https://github.com/scaffold-eth/scaffold-eth/blob/buyer-mints-nft/packages/hardhat/deploy/00_deploy_your_collectible.js#L13) and I had to specify a `--network` flag when running my local hardhat node, otherwise it complained.
If you'd like to jump into that build guild and show me up as the noob I really am, nothing would delight me more :heart:
> Make QuickStart actually Start

- packages/react-app/src/views/CommitReveal.jsx
Input value in Calculate hash card (commit reveal view) now gets properly converted to bytes32 when clicking change to bytes32 button instead of only converting 'scaffold-eth' to bytes32 in a hardcoded manner
> fix(string->bytes32)

- packages/react-app/src/components/Contract/index.jsx
- Fix for overloaded functions in the Contract component -> no overloaded functions would show up as function lookup on the contract object was undefined (needed to be the full signature with args)
- e.g. loogie-tank branch on Mainnet LOOG tab
> Contract component function overloading fix

- packages/react-app/src/constants.js
Last month, Avalanche decreased their gasPrice from 225 gwei to 25 gwei
> Updated default gasPrice for Avalanche Mainnet

- packages/hardhat/hardhat.config.js
Optimistic Kovan now runs pure EVM so the OVM configuration is no longer required (will actually break if enabled). Gas price can also no longer be zero.
> fix: remove OVM configuration from kovanOptimism

- packages/hardhat/deploy/00_deploy_your_contract.js
- packages/react-app/src/App.jsx
- packages/react-app/src/components/DEX.jsx
- packages/react-app/src/components/index.js
While going by step by step instructions, I have found some bugs or missing code that I think might make it difficult for a user to finish challenge if that person is not familiar with react (_Checkpoint 6: UI_ code is broken).
`dex` variable was missing in the `00_deploy_your_contract.js` script + there was a lot of issues that I addressed, that were related to some imports missing or wrong order of parameters in the react app (most of it in `DEX.jsx`) + injectedProvider has not been passed to the component. Please review attached commits. Tested on my environment and it works. Maybe not the most optimal way, but I'm not an expert.
Still there is an error being thrown by _safeMath_ lib from `DEX.sol` when withdrawing the liquidity from dex, but that will be addressed in another pull …
> Challenge 3 dex fix react dex component

- packages/react-app/src/App.jsx
Punk wallet is currently broken for transactions due to the replay-protection update. It appears that replay protected transactions require the chainID when forming the transaction. Can someone confirm if this works? You should be able to send Matic via the punk-wallet app.
> Punk Wallet Network Fix

- packages/react-app/src/components/Contract/utils.js
JSON.stringify() on array type response values leaves bignumber object hard to read
ISSUE:
FIX:
> displayvariable: improve readability for bignumbers within arrays/tuples

- packages/hardhat/deploy/00_deploy_your_contract.js
The deployment script usually throws an error if we attempt contract verification immediately after deployment. Etherscan has not yet indexed the data, I suppose.
There is a huge error message in the console and the user needs to run the verification separately.
Since deployments on testnet require some waiting anyway, I guess it's acceptable to add a few seconds in order to avoid the issue described.
> wait a bit before verifying a contract post-deployment

- packages/react-app/src/App.jsx
- packages/react-app/src/components/NetworkDisplay.jsx
- yarn.lock
**Improve network switch initialization**
It selects your intended network instead of defaulting to the first option and alerting you in case it doesn't match.
**Improve network mismatch alert** -
If you want to work on localhost but are logged in with an injected provider the alert suggests you switch to localhost. I found some things don't work as expected when working locally via metamask (like switching accounts and having correct balance updates).
So I've added a special handling for this case: It suggest you logout from the injected provider.
> Network UX

- packages/hardhat/hardhat.config.js
Constants.js in react-app does not include "polytest" in NETWORKS.
So when a user deploying with hardhat.config enters "polytest" as defaultNetwork, they may do the same in App.jsx.. which would error.
Just switching it to match constants.js.
> hardhat.config update 'polytest' to 'mumbai' to match constants.js

- packages/react-app/src/components/Contract/DisplayVariable.jsx
- packages/react-app/src/components/Contract/index.jsx
- packages/react-app/src/components/Contract/utils.jsx
- packages/react-app/src/constants.js
This fixes using the correct block explorer in Contract component (address views).
On the way it also fixes Harmony name in constants to be as the object key (app depends on it to get the RPC correctly).
> fix block explorer in contract component

- packages/react-app/src/App.css
For example, when the wallet modal appears the page height is 100% and so there is no scrollbar. But then when the modal disappears the scrollbar comes back and the page shifts. This CSS is a transparent solution to the problem (see https://stackoverflow.com/a/30293718/25068)
> Prevent page from moving when scrollbar appears / disappears

- packages/react-app/src/views/Hints.jsx
fixes #632 
The issue was caused by `listOfTokens` containing tokens which have duplicate symbols (CMI, for example). As these symbols were not unique but used as keys for the `Option` components, it caused React to duplicate/overwrite list items while scrolling.
> Fixed token selector duplicating items

- README.md
- Adds limited documentation to specify the node version to use.
- Experience issue described [here](https://github.com/scaffold-eth/scaffold-eth/discussions/670) when using current version of node.
> Added documentation to specify node version 

- packages/hardhat/hardhat.config.js
- packages/hardhat/package.json
Bump the version of hardhat-etherscan and change the yarn verify command to use the new format to allow support for multiple API keys for different EVM chains.
See: https://github.com/NomicFoundation/hardhat/issues/1448
> Update Hardhat etherscan to support multiple API keys

- packages/react-app/src/hooks/TokenList.js
I noticed whenever a chain id is passed to the useTokenList hook, the returned list is always undefined due to the fact that it's being set to `_tokenList.tokens` after filtering by `chainId`.
> tokenlist minor bug

- packages/react-app/package.json
- yarn.lock
Optimism just released the 1.0.0 version of the [Optimism SDK](https://www.npmjs.com/package/@eth-optimism/sdk). The Optimism SDK handles interactions between Optimism and Ethereum cleanly, making it easy for users to create cross-chain Optimism applications. It also contains utilities that simply the process of estimating gas for Optimism transactions (since Optimism's current fee scheme is somewhat different from that of Ethereum).
I noticed that the Arbitrum SDK is being included in scaffold-eth by default, so I think it also makes sense to include the Optimism SDK too:
https://github.com/scaffold-eth/scaffold-eth/blob/70098ab3443f8552beb185687bccfe9c5ccebbf6/packages/react-app/package.json#L33
I'd also be great to get a forkable bridge example that uses the SDK. Should be super easy!
> feat: include Optimism SDK by default

- packages/react-app/package.json
Hi @austintgriffith ,
I noticed that I cannot transfer funds with PunkWallet on the Polygon chain.
After debugging the code it turned out to be an ethers bug, which is now fixed in the latest version - 5.5.6.
Here is the ethers issue:
https://github.com/ethers-io/ethers.js/issues/2691
**Note:**
Actually PunkWallet still doesn't work on Polygon, because the gasPrice is set to 1gwei, which is not enough right now.
I can look into this later, manually setting the gasPrice worked for me, my transaction was confirmed.
Best,
Tamas
> PunkWallet doesn't work on Polygon

- packages/hardhat/scripts/upload.js
IPFS now throws "TOO MANY REQUESTS" error when calling API directly within loop of more than a few items. 
Use Promise.all with promise-wrapped setTimeout to throttle API calls by `DELAY`.
> Use promise-wrapped setTimeout for API throttling

- packages/react-app/scripts/ipfs.js
The ipfs script uses an different API from an older version of the package `ipfs-http-client`. I have updated the script to work with `ipfs-http-client@55.0.0` which is the version that is installed when running `yarn install`.
Currently, running `yarn run ipfs` on the master branch is broken.
I have updated the ipfs script to match the new API in the library ipfs-http-client@55.0.0 in this pr.
> Updated IPFS script to use newer API from 'ipfs-http-client'

- packages/react-app/src/views/Subgraph.jsx
- packages/services/graph-node/docker-compose.yml
Currently breaks on startup using more recent ipfs version, this pins the version and adds an additional hint to the subgraph page
> pin ipfs version, add note on chain running

- packages/hardhat/hardhat.config.js
- packages/react-app/src/constants.js
Adds Moonbeam networks and related information such as chain ID and RPC endpoints to the Hardhat and React config files. 
The project [works well with Moonbeam](https://docs.moonbeam.network/builders/build/eth-api/dev-env/scaffold-eth/), and would be good to have the networks listed in the configuration files.
> Adds Moonbeam network information

- packages/react-app/src/hooks/GasPrice.js
I think https://ethgasstation.info/ is broken.
Currently the legacy fast gas price is lower than the base fee, therefore the transaction cannot be sent.
I switched to etherscan, "SafeGasPrice" is the lowest option, I could speed up a few transactions.
Also I set ~4 seconds for polling, because otherwise I run into errors, when the gas price was increasing, the old gasPrice wasn't enough.
Best,
Tamas
> Punk wallet fix gas price api

- packages/react-app/package.json
- yarn.lock
Right now it's not possible to eject with react-scripts. We need to update `react-scripts` package to `v4.0.1` according to https://stackoverflow.com/questions/64979793/error-cannot-find-module-react-dev-utils-inquirer
> fix eject with react-scripts

- packages/react-app/src/App.jsx
Copy-pasting a wrong link accidentally, or simply typing something in the "wallect connect url" input breaks the app.
It won't load at all until we remove "walletConnectUrl" from localStorage.
> Remove walletConnectUrl from localStorage in case the connection wasn't successful.

- packages/hardhat/hardhat.config.js
- packages/hardhat/package.json
Added hardhat-abi-exporter to dependency list of hardhat. This helps when there are multiple contracts and one contract is uses as state inside another. At deploy time we can only export deployed contracts abi but sometimes need arises where you want to call function of contract that is used as state inside deployed contract. 
This plugin exports abi of all the contracts inside "../react-app/src/contracts" with same name as contracts inside a json file for each contract. You can just export abi and create the Read/WriteContract using the address of state contacts and abi.
Usecase:
MultiISigWallet uses as state inside MultiSigFactory and MultiSigFactory gets deployed and you dynamically create MultiISigWallet and want to call function of MultiISigWallet
> Add hardhat-abi-exporter plugin

- packages/hardhat/hardhat.config.js
Make contracts directory cleaner by separating exported ABI from deployed contracts
> Export ABI to a sub directory instead of contracts directory

- packages/react-app/src/components/Header.jsx
- packages/react-app/src/constants.js
fix prettier warnings 
```Compiled with warnings.
src/components/Header.jsx
Line 6:33:  Replace `link,·title,·subTitle` with `·link,·title,·subTitle·`                                                                                                                    prettier/prettier
Line 9:18:  Replace `⏎········title={title}⏎········subTitle={subTitle}⏎········style={{·cursor:·"pointer"·}}⏎·····` with `·title={title}·subTitle={subTitle}·style={{·cursor:·"pointer"·}}`  prettier/prettier
Line 16:2:  Delete `⏎`                                                                                                                                                                        prettier/prettier
Line 23:2:  Insert `;⏎` …
```
> fix prettier warnings

- packages/react-app/src/App.jsx
- packages/react-app/src/components/Account.jsx
- packages/react-app/src/components/FaucetHint.jsx
- packages/react-app/src/components/Header.jsx
- packages/react-app/src/components/NetworkDisplay.jsx
- packages/react-app/src/components/Wallet.jsx
Currently the balance and address (in the `Account` component) overlap with the logo on smaller screens.
This PR introduces style and component changes that improve the header responsiveness as well as the general UI of the account component such as:
- smaller address and balance font size
- removing the fixed positioning of the account component in favour of using flex box styles in the `Header` component
- placing the long subtitle string under the main logo
**Desktop:**
**Phone screen:**
**Cluttered header with network selector also work most of the time:**
> Improving header and account responsiveness

- packages/react-app/src/App.jsx
When two punk wallets were connected, the speed up option wasn't working on the wallet punk-wallet.
> Punk wallet speed up wallet connect

- packages/react-app/src/App.jsx
Hey guys,
This PR is about Wallet Connect, it should do the following:
1. Display the Dapp's icon instead of the green checkmark
2. Cleans up Wallet Connect from localStorage, when the Dapp has disconnected (previously the green checkmark was still visible)
3. We should be able to connect to another Dapp, without deleting the old session manually (just shoot the new Dapp's QR code)
4. Update the Dapp with the new adress/chainId we selected (ENS handles the new chain quite weirdly)
5. Display a spinner when we're waiting for the connection (sometimes it took 5-10 seconds for me, other times it's very fast)
> Punk wallet wallet connect update

- packages/react-app/src/views/Subgraph.jsx
it just update the old link https://thegraph.com/docs/define-a-subgraph to the graph docs on the subgraph demo page that its returning 404 now to the new one https://thegraph.com/docs/en/developer/create-subgraph-hosted
> fix(react-app): update old subgraph docs link

- packages/react-app/src/components/Contract/FunctionForm.jsx
- packages/react-app/src/views/Subgraph.jsx
There was some (non-working) display logic to show a different button copy & icon depending on the type of the contract call (read vs write txs). Read 📡 VS. Send💸
It was always showing the "send 💸" button.
It should be fixed now. It's just a little thing but I think it helps with the mental model (reads VS. write txs)
Before:
After:
Also fixed some prettier warnings in the console.
> Show the correct button copy & icon on the Contract component

- packages/react-app/src/App.test.js
Delete testing template (added by create-react-app) which isn't designed to work with Scaffold-eth.
This template is more misleading than helpful atm. A better solution would be to adapt it to Scaffold. If it's needed, please reply in discussion what kind of adaptation would be merged, so that PR could be improved.
> delete file App.test.js from React-app

- README.md
- packages/hardhat/scripts/mint.js
- packages/react-app/src/App.jsx
Infura does not offer a public and free IPFS upload feature anymore, so you need to use project id and project secrets to authenticate
> Add Infura IPFS Authentication for simple NFT example

- packages/react-app/src/App.jsx
- packages/react-app/src/components/Balance.jsx
- packages/react-app/src/components/FaucetHint.jsx
- packages/react-app/src/components/TokenBalance.jsx
- packages/react-app/src/constants.js
- packages/react-app/src/helpers/index.js
- packages/react-app/src/helpers/rpc.js
- packages/react-app/src/hooks/useStaticJsonRPC.js
- When you send funds through the faucet it takes around `5 sec` to reflect since `RPC_POLL_TIME = 5000` which I think is a bit slow for local development.
- If you try setting `purpose` through the `ExampleUI` tab it again takes `5 sec` to update the purpose which is slow. 
- Another problem is let's suppose a builder creates a new `Contract` and tries to read from the contract  using `useContractReader` hook and fails to pass `pollInterval` in arguments, Now if the value updates it will take **`50 sec`** to reflect that in `UI` due to ` _p.pollingInterval = 50000;` in `useStaticJsonRPC.js`. Since `useContractReader` updates the values when new block is added when `pollInterval` argument is not passed or it is passed as `0` and since `_p.pollingInterval` is set to `50000` it will check …
> updated the logic to use no polling when on localhost and increased pollTime for mainnet calls

- packages/hardhat/contracts/YourContract.sol
On the sample smart contract `YourContract` we have the function `setPurpose`. When we interact with the ExampleUI we can call this function with ETH value which makes the transaction revert, when we perform `Set Purpose With Value`action.
This PR changes the function `setPurpose` to payable.
**Before**
[non-payable-function.webm](https://user-images.githubusercontent.com/54408225/194826386-f8bf6361-0c87-4df2-a830-54072dd9a0c3.webm)
**After**
[Screencast from 09-10-22 12:54:53.webm](https://user-images.githubusercontent.com/54408225/194752884-9b364cf7-8d09-4571-9aa1-fa40cc72ec4b.webm)
> Make `setPurpose` function payable for fixing revert function on ExampleUI interactions

- packages/react-app/package.json
- packages/react-app/public/manifest.json
- packages/react-app/src/App.jsx
- packages/react-app/src/helpers/Web3ModalSetup.js
- yarn.lock
this sets up scaffold-eth to work as a "Safe" app out of the box
we just used the web3-modal wrapper:
https://github.com/safe-global/safe-apps-sdk/tree/master/packages/safe-apps-web3modal
this is really handy because now you can make a quick scaffold-eth app and then iframe it into a gnosis Safe or a multisig.lol
> scaffold-eth apps should be safe apps!

- packages/hardhat/hardhat.config.js
This updates the default address for localhost in the hardhat-config.js file due to yarn deploy failing.
Should close #927
> 927 update default network address

- README.md
- packages/hardhat/deploy/00_deploy_your_contract.js
- packages/hardhat/package.json
- packages/react-app/src/constants.js
- Added Sepolia to constants.js
- Updated hardhat-deploy version to ^0.11.23
- Updated deploy script to work with ^0.11.23
- Updated ReadMe to remove Node 18 side quest and mentions of Node 16
> Add Sepolia Support & update hardhat-deploy version
