scaffold-eth/scaffold-eth

packages/react-app/src/App.js
packages/react-app/src/SmartContractWallet.js
packages/react-app/src/components/Address.js
packages/react-app/src/components/Balance.js
packages/react-app/src/components/Faucet.js
packages/react-app/src/components/Header.js
packages/react-app/src/components/Provider.js
packages/react-app/src/components/Timeline.js
packages/react-app/src/helpers/Transactor.js
packages/react-app/src/hooks/Balance.js
packages/react-app/src/hooks/BlockNumber.js
packages/react-app/src/hooks/ContractReader.js

[WIP] Lint cleanup

---

packages/react-app/src/components/Contract/index.jsx

Contract now queries the `stateMutability` to see whether the function should be read or allow the user to kick off a transaction
see for previous behaviour: https://youtu.be/oMamr_3Vbso?t=1418

fix: properly display state changing functions with no args

---

packages/react-app/src/App.jsx
packages/react-app/src/GithubIssue.jsx

Display Github issues with details

Display github issues

---

packages/react-app/src/components/Contract/DisplayVariable.jsx

Put back refresh button that was removed in PR ([Auto refresh DisplayVariable #44](https://github.com/austintgriffith/scaffold-eth/pull/44))

Put back refresh button in DisplayVariable

---

packages/buidler/buidler.config.js
packages/buidler/package.json
packages/buidler/scripts/deploy.js
yarn.lock

- leading '0x' removed from the abi encoded args written to a file
- added goerli test network
- added generation of the abi encoded args file if deploying (not just auto deploying)
- refactored the deploy.js so it reads a bit easier, imho
tested as is
tested with added solidity contract file, everything compiles and deploys like before

Refactored some of the things as per our call today (02/11/2020)

---

packages/react-app/.eslintrc.js
packages/react-app/src/App.jsx
packages/react-app/src/components/Address.jsx
packages/react-app/src/components/AddressInput.jsx
packages/react-app/src/components/Contract/DisplayVariable.jsx
packages/react-app/src/components/Contract/FunctionForm.jsx
packages/react-app/src/components/Wallet.jsx
packages/react-app/src/hooks/ContractReader.js
packages/react-app/src/hooks/EventListener.js
packages/react-app/src/hooks/LookupAddress.js
packages/react-app/src/hooks/ResolveName.js
packages/react-app/src/hooks/UserProvider.js
packages/react-app/src/views/ExampleUI.jsx
packages/react-app/src/views/Hints.jsx
packages/react-app/src/views/Subgraph.jsx

This fixes a bunch of eslint warnings which were cluttering up the console and making it very hard to see any new issues being introduced.

Fix eslint warnings

---

packages/hardhat/scripts/deploy.js

Allows you to give some ETH to your contract on deploy

Payable constructor

---

README.md

Contact diff unintended, seems GH error.

fix directory change in readme

---

packages/buidler/contracts/INiftyToken.sol
packages/buidler/contracts/NiftyInk.sol
packages/buidler/contracts/NiftyToken.sol

- Added ownership transfer logic in ink contracts

Ink Ownership Transfer

---

.gitpod.yml
README.md

This PR includes a `.gitpod.yml` with a configuration that set-up an environment with everything on the Quick Start section ready. 
A great solution to jump right away into coding and learning. No Node, Yarn, or Git requirements. Everything handles automagically.
You can try a demo here: https://github.com/0xGabi/scaffold-eth-demo

Add Gitpod configuration

---

packages/react-app/src/App.jsx

Simply added the missing `Alert` component from antd.

Add missing `Alert` on staking-app-tutorial branch

---

packages/react-app/src/App.jsx

1-metamask not connected: refreshes webpage when user changes network…
2-metamask account change: currently webpage didnt refresh when user change account in metamask. its causes the error.

1-metamask not connected: refreshes webpage when user changes network

---

packages/hardhat/contracts/Auction.sol
packages/react-app/src/App.css
packages/react-app/src/App.jsx

- removed global staking and instead added individual staking for nft's

Updated Staking logic for bidders

---

packages/react-app/src/App.jsx
packages/react-app/src/helpers/Transactor.js
packages/react-app/src/hooks/ContractLoader.js
packages/react-app/src/hooks/ExchangePrice.js
packages/react-app/src/hooks/GasPrice.js
packages/react-app/src/hooks/TokenList.js

A stab at solving #198.
With these fixes, if you are offline and you still want to code while on localhost + local chain, you should not get any errors from the components that are looking for stuff on mainnet.
It doesn't solve the issue when you go to Chrome's console -> network -> simulate offline, 
BUT it does work fine when you are truly offline or in airplane mode.

Sanity checks for when connection is offline

---

packages/hardhat/contracts/YourContract.sol
packages/hardhat/hardhat.config.js
packages/hardhat/package.json
packages/react-app/src/helpers/Transactor.js
yarn.lock

- Upgrades to Hardhat 2.4.0
- Adds example in YourContract.sol on how to define a custom error w/params (new in Solidity 0.8.4) and how to revert with it.
- Updates transactor to show error data if it exists.
*Note: Waffle/Chai does not yet support custom errors so I didn't add a test for it yet.

Hardhat 2.4.0 and Custom Errors sample

---

packages/react-app/src/hooks/ContractReader.js

@azf20 Implemented your fix for #185 in a clean branch fresh from master.
Gave it a try and it does fix the issue I reported.
Unless in this time you found a fix you like more, we should merge this one.

Implemented setTried change to useContractReader

---

packages/react-app/src/helpers/Transactor.js

Find the error message when using ethers js signer

---

.gitignore
package.json
yarn.lock

Updates to remove caniuselite warning

---

packages/react-app/src/components/Account.jsx
packages/react-app/src/components/Faucet.jsx

To fix https://github.com/austintgriffith/scaffold-eth/issues/258 and https://github.com/austintgriffith/scaffold-eth/issues/265

fix faucet and account wallet

---

packages/niftygraph/package.json
packages/react-app/package.json
packages/react-app/public/index.html
packages/react-app/src/ViewInk.js
packages/react-app/src/helpers/Ipfs.js
yarn.lock

- Show image if it's a large ink (rather than rendering on the canvas)
- Loading and status indicator for the play button
- Optimise ipfs fetching (concat library)

View optimisations

---

packages/react-app/src/App.jsx
packages/react-app/src/hooks/ContractLoader.js
packages/react-app/src/hooks/ContractReader.js

- setTried in contractReader
- React to changes in the customAddresses in the contract loader
- Use a URL that works for WalletConnect

Small bugs

---

packages/react-app/package.json
yarn.lock

- ^ was using a version that left aligned menus

pin antd version

---

packages/react-app/src/components/Wallet.jsx

Was using the provider to make transactions from the Account wallet, fixed to use the signer.

fix wallet.jsx

---

README.md

Readme updates to document possible areas of further development.

Defi smile donations

---

packages/hardhat/package.json
packages/react-app/package.json

Upgrade packages for new fee structure

Upgrade for London

---

README.md
packages/react-app/src/components/ImageToIPFS.jsx

Readme update per discussion in telegram group. More info added related to how the IPFS side of things works.

Readme updates per telegram discussion

---

packages/react-app/package.json

Follow up on https://github.com/austintgriffith/scaffold-eth/pull/353#commitcomment-55745050

Ignore unwanted folders for prettier

---

packages/hardhat/hardhat.config.js

Theres an issue with Hardhat where MetaMask mistakenly assumes all networks with http://localhost:8545 have a chain id of 1337
https://hardhat.org/metamask-issue.html
This made the challenge app crash on load.
For now, I am updating the code so that you can see exactly what needs to be done to resolve the issue. But I think this is probably better suited for a comment in the tutorial README

Challenge 1: Call out Hardhat bug fix

---

README.md
packages/hardhat/package.json
packages/react-app/package.json
packages/react-app/src/App.jsx

eip 1559 : Gas prices calculator

---

package.json

This just adds a single repo that yarn said was missing when i first installed it.  Unbreaks the repo from that issue...
Suggested edit only, feel no need to accept my proposed change.

Add missing dep that causes issues with network pointer

---

README.md

Deep dive into some concepts, probably the readme should be edited because this comes straight from my implementation and it has a lot of personal point of view (point of view from a newbie implementing it)

Update a readme with a more long explanation

---

README.md

Fix the path in README.md

---

packages/react-app/package.json

📦 update eth-hooks versison

---

README.md

Is it yarn deploy or?  If it is then please accept my request. :)  thank you for all your work!!!

Updating Readme.md with syntax error correction?

---

packages/react-app/src/App.jsx

Ethers.utils and duration imported fixed some undefined errors. 
Removed address from withdraw function as example uses msg.sender.

App.jsx changes to work with staking contract example

---

README.md

Reverts scaffold-eth/scaffold-eth#417

Revert "Updated readme with more explanations/test"

---

packages/react-app/package.json
packages/subgraph/package.json

dependency update

---

packages/hardhat/package.json
packages/react-app/src/App.jsx
yarn.lock

Update the version of open zeppelin in the package.json file to v4

upgrade oz to ^4

---

packages/services/graph-node/docker-compose.yml
packages/subgraph/package.json
packages/subgraph/src/mapping.ts
packages/subgraph/src/subgraph.template.yaml

fix graph-node versioning

---

packages/react-app/src/App.jsx

Update stake events arguments to fix bug so that events are displayed

Stake events list mapping bug fix

---

packages/hardhat/contracts/LoogieTank.sol

I made same changes on the movement from the Loogies in the tank. 
Now the loogies are moving to the left with a speed based on the gen 0 from the loogie.
The movement is one speed unit to the left for each block. When the left edge is reached, the loogie go to the right edge (I used just 256 size, but I didn't change the rect size).

Loogies moving on x axis to the left in the tank

---

packages/hardhat/test/myTest.js

Hey guys,
It took me a while to figure it out how this can be done, maybe someone else will find this useful.
I commented out the new code, because it only makes sense when the SetPurpose event is emitted from YourContract.
Best,
Tamas

Example for testing events

---

README.md
packages/hardhat/hardhat.config.js
packages/hardhat/package.json
packages/react-app/src/App.jsx

Flemjamins and burnable loogies

---

packages/hardhat/deploy/00_deploy_your_contract.js
packages/react-app/src/App.jsx

Just poking around and getting started!

Staker staging

---

README.md

Hey @austintgriffith, this will make it easy for devs to just get up and running using the existing Gitpod config

Added gitpod button

---

README.md

Challenge 2 token vendor typo in instructions

---

packages/services/graph-node/docker-compose.yml

In the Docker compose file for graph-node

Use latest ipfs tag

---

packages/react-app/src/components/Account.jsx
packages/react-app/src/components/Address.jsx
packages/react-app/src/components/AddressInput.jsx

This cleans up the Account/Address/AddressInput components:
Essentially I've just made it to where there's a more clear delineation between:
- State/Props variables (at the top)
- Utility functions for the component (in the middle) 
- JSX componentry (in the return functions at the bottom)
The more separated these are the more legible the component is and much easier to read/grok, IMO. 
Happy to do some more too, but figured I'd check to see if you guys like the work before going crazy 😛 
Awesome work btw @austintgriffith ...thanks for providing this to the community

Cleanup components

---

packages/react-app/src/components/Balance.jsx
packages/react-app/src/components/EtherInput.jsx
packages/react-app/src/components/Faucet.jsx
packages/react-app/src/components/Swap.jsx
packages/react-app/src/components/ThemeSwitch.jsx

Component cleanup in the same vain as #550 @codenamejason

Component cleanup

---

packages/hardhat/hardhat.config.js
packages/hardhat/package.json

Update optimism config

---

packages/react-app/src/components/Contract/FunctionForm.jsx

issues-568: Clear form on successful submit

---

packages/hardhat/hardhat.config.js

Add error handling to yarn account command

---

packages/react-app/src/App.jsx
packages/react-app/src/components/Account.jsx
packages/react-app/src/components/FaucetHint.jsx
packages/react-app/src/components/NetworkDisplay.jsx
packages/react-app/src/components/index.js
packages/react-app/src/helpers/Web3ModalSetup.js
packages/react-app/src/helpers/index.js
packages/react-app/src/views/Home.jsx
packages/react-app/src/views/index.js

- Extracts `faucetHint` & `NetworkDisplay` logic and UI into components
- Create web3Modal setup into helpers
- Add `Home.jsx` as the default view when app loads

App.jsx clean up

---

packages/react-app/src/App.jsx
packages/react-app/src/components/NetworkSwitch.jsx
packages/react-app/src/components/index.js
packages/react-app/src/hooks/useStaticJsonRPC.js

Network Switch component

---

docker/README.md
docker/setup.sh

Closes #527 
I have improved a little bit the Docker documentation and modified the script and code blocks to check if the container exists before attempting to do anything with it.
I think people getting started with Docker will be less confused with this changes.
I have also added little instructions for potentially Windows users.

Improve Docker docs and setup.sh script to check for runnning container

---

docker/setup.sh

Fix typo in setup.sh

---

packages/react-app/src/components/Contract/utils.js

fix: https://github.com/scaffold-eth/scaffold-eth/issues/595#issue-1071567179

fix/update utils.js

---

packages/react-app/src/components/Address.jsx

display address in standarized hidden format

---

README.md
packages/react-app/package.json
packages/react-app/src/App.jsx
packages/react-app/src/components/Account.jsx
packages/react-app/src/components/NetworkDisplay.jsx

Adde most of the changes made by @codenamejason

Optional burner wallet support

---

packages/react-app/src/components/Address.jsx

Fix Address link

---

packages/react-app/src/App.jsx
packages/react-app/src/components/Account.jsx
packages/react-app/src/components/FaucetHint.jsx
packages/react-app/src/components/NetworkDisplay.jsx

- When `USE_NETWORK_SELECTOR` flag is set to false
- When `USE_NETWORK_SELECTOR` flag is set to true

Account UI fix

---

packages/react-app/src/helpers/Transactor.js

Reverts scaffold-eth/scaffold-eth#602

Revert "Add Optimism kovan and mainnet chain ids to transactor notify"

---

packages/hardhat/hardhat.config.js
packages/react-app/src/App.jsx
packages/react-app/src/components/EtherInput.jsx
packages/react-app/src/constants.js

This is a PR for the punk-wallet to add support for Harmony and Harmony Testnet blockchain.

feat: add support for harmony and harmony testnet

---

packages/react-app/src/views/Home.jsx

None
This commit fixes the path of Home.jsx file shown on the home page of the React app.
See image below for reference

fix path of Home.jsx file

---

packages/react-app/src/constants.js

Use the recommended RPC and block explorer URLs from https://docs.polygon.technology/docs/develop/network-details/network

Update polygon and mumbai configs with latest URLs

---

packages/react-app/src/components/MultiAddressInput.jsx
packages/react-app/src/components/index.js

How to use:
```
<MultiAddressInput ensProvider={mainnetProvider} onChange={handleChange} />
```

Feature: Multi Address Input Component

---

packages/react-app/package.json
packages/react-app/src/components/TokenSelect.jsx
packages/react-app/src/components/index.js

```js
<TokenSelect
chainId={1}   // chainId to filter with, defaults to mainnet (1)
localProvider={localProvider} // provider for loading unlisted token from address
nativeToken={{ name: "Native Token", symbol: "ETH" }}  // network native token name and symbol
/>
```

Feature: TokenSelect component

---

packages/hardhat/contracts/YourContract.sol

- Events are a good practice to learn about
- Current default to comment them out breaks the subgraph example

Uncomment event

---

packages/react-app/src/components/Header.jsx

instead of hard coding the link, title and
subtitle, it is replace with default props. This
makes header component more dyanmic

make Header component more dynamic

---

packages/react-app/src/components/TransactionResponseDisplay.jsx
packages/react-app/src/helpers/TransactionManager.js

Punk wallet cancel tx

---

README.md

Update link to commit-reveal-with-frontend

---

packages/react-app/src/components/TransactionResponseDisplay.jsx

------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------

Polish the UI

---

foundry.toml
packages/hardhat/test/Foundrytests/YourContract.sol
packages/hardhat/test/Foundrytests/test.sol
packages/hardhat/test/Foundrytests/test/YourContrat.t.sol

Demo tests for anyone to start writing tests in Foundry easily. Welcome any suggestions!

Foundry tests in ScaffoldEth

---

README.md
packages/hardhat/contracts/Marketplace.sol
packages/hardhat/contracts/MockERC20.sol
packages/hardhat/contracts/MockERC721.sol
packages/hardhat/deploy/00_deploy_your_contract.js
packages/hardhat/hardhat.config.js
packages/react-app/scripts/ipfs.js
packages/react-app/scripts/s3.js
packages/react-app/src/components/Contract/FunctionForm.jsx
packages/react-app/src/components/Header.jsx
packages/react-app/src/components/MarketplaceEvents.jsx
packages/react-app/src/components/TokenEvents.jsx
packages/react-app/src/constants.js
packages/react-app/src/hooks/GasPrice.js
packages/react-app/src/index.css
packages/react-app/src/views/Home.jsx

Dapp updates to accept any ERC721 and any ERC20. Comments updated everywhere

Simple marketplace royalties

---

packages/hardhat/hardhat.config.js
packages/react-app/src/constants.js

This complete PR #731 by adding Arbitrum networks to both react-app and hardhat.

Add Arbitrum networks

---

packages/react-app/src/App.jsx
packages/react-app/src/components/WalletConnectTransactionDisplay.jsx
packages/react-app/src/components/index.js

Hey guys,
This PR is about the wallet connect pop up, I tried to make it a little bit more readable, also I made some simple changes:
1. The title should reflect the method, e.g. "Sign Transaction?" when signing a message instead of the old hard coded "Send Transaction?"
2. ENS name is displayed (only on Ethereum)
3. The Dapp will know when we select "Cancel" on the pop up
4. In case of  eth_signTransaction/eth_signeTypedData the raw hash is returned, instead of the object.
I used https://github.com/WalletConnect/walletconnect-example-dapp and punk wallet (as a Dapp) for testing.
Cheers,
Tamas

Punk wallet enchance wallet connect

---

packages/react-app/package.json
packages/react-app/src/components/TransactionHistory.jsx
packages/react-app/src/components/TransactionResponseDisplay.jsx
packages/react-app/src/helpers/TransactionManager.js
yarn.lock

Punk wallet transactions scroll

---

packages/react-app/src/components/TransactionHistory.jsx
packages/react-app/src/components/TransactionResponseDisplay.jsx

Do not use Infinite Scroll by default.

---

packages/react-app/src/App.jsx

Change default network to Goerli

---

packages/hardhat/hardhat.config.js

https://twitter.com/etherscan/status/1569311894279958531

Update: Rinkeby & Ropsten deprecated warning

---

packages/react-app/src/App.jsx
packages/react-app/src/components/Header.jsx

Cleaned prettier errors in header.jsx, and updated the Roll The Dice button to enable every time.

Prettier errors and button fix

---

README.md
packages/react-app/src/App.jsx
packages/react-app/src/components/Balance.jsx
packages/react-app/src/components/FaucetHint.jsx
packages/react-app/src/components/TokenBalance.jsx
packages/react-app/src/constants.js
packages/react-app/src/hooks/useStaticJsonRPC.js
yarn.lock

#CHANGES MADE FOR THIS ISSUE
https://github.com/scaffold-eth/scaffold-eth/issues/882
changes: 
1. In this pr changed useStaticJsonRPC hook. 
instead of initiating 2-times useStaticJsonRPC hook for localProvider and mainnetProvider  accepting 
localUrl, urlArray, isMainnet as parameters and giving back localProvider and mainnetProvider at 1 call. 
2. also added logic for if it is mainnetHook then  use localProvider as mainnetProvider only creating 1 provider. 
3. added loadMainnetProvider function inside useStaticJsonRPC to get the mainnetProvder from an array. at old logic, the promise.race()  calls all the rpc's in array . but in loadMainnetProvider it calls first RPC if it detects the network and then skips other 2 calls else it will call another RPC in array etc. 
4. other minor …

Hotfix/  rpc polling issue proposal 1

---

packages/react-app/package.json

this fixes:
Error: error:0308010C:digital envelope routines::unsupported

fix on node 18

---

packages/react-app/src/styles/homepage.css

https://user-images.githubusercontent.com/80153681/207373019-95c7ab45-ca74-4cde-9d98-c1ee43208f0b.mov
https://user-images.githubusercontent.com/80153681/207373168-cdd6e737-c917-47d8-a12b-0e3246ee89b4.mov

update the reponsiveness for hero section

---

packages/react-app/src/App.jsx
packages/react-app/src/hooks/GasPrice.js
packages/react-app/src/hooks/index.js

https://docs.etherscan.io/api-endpoints/gas-tracker#get-gas-oracle

Use local gas price hook using etherscan api

---

README.md

Adds come copy around deployments.

add some context to readme

---

packages/react-app/src/views/Home.jsx

the home page is where most folks start reading and it needs this line about how to deploy i think

add a better hint about how to deploy

---

README.md

🧪 Quickly experiment with Solidity using a forked private testnet, from the mainnet, and swapping tokens from Uniswap
**Scaffold-Eth x Buildbear** lets you create your own private testnet, (optional) forked from the mainnet, with your own native token and ERC20 Token faucet and blockchain explorer
- Create your own private testnet
- Use your personal Native token faucet
- Use your personal ERC20 faucet
- Swap your tokens on Forked Uniswap
Demo Video --> [here](https://docsend.com/view/ctc8zhhgtuscf7if)

Updating ReadMe for the BuildBear Flavour
